apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: arcagenttestacr.azurecr.io/azvote/azure-vote-front
    newTag: bfa9d563d59bee11b16f7f57817c84ce2de26b13
  - name: arcagenttestacr.azurecr.io/azvote/azure-vote-back
    newTag: bfa9d563d59bee11b16f7f57817c84ce2de26b13
resources:
  - manifests.yaml