apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: arcagenttestacr.azurecr.io/azvote/azure-vote-front
    newTag: 3020bb97e9ccb94c84e8854edbe0f7b63fd0adf0
  - name: arcagenttestacr.azurecr.io/azvote/azure-vote-back
    newTag: 3020bb97e9ccb94c84e8854edbe0f7b63fd0adf0
resources:
  - manifests.yaml