apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: arcagenttestacr.azurecr.io/azvote/azure-vote-front
    newTag: f8af00d34c2bae2bc0c9f5d9b0a971b823d42b29
  - name: arcagenttestacr.azurecr.io/azvote/azure-vote-back
    newTag: f8af00d34c2bae2bc0c9f5d9b0a971b823d42b29
resources:
  - manifests.yaml